### ISSUE TITLE
Underlying Asset Decimals - Pod Token Matching the Underlying Token

### ISSUE THREAD

**Issue by kamescg** [pooltogether/pods-v3-contracts#11]
In the Pod contract we initialize the `token` with IERC20Upgradable interface which unfortunately doesn't have the `decimals` function.

Instead of switching the  `interface` for the token, a potential approach could be adding a utility function for calling the token contract directly using an encoded function selector and retrieving the decimals in bytes format.

In short, opting for a direct call and using a few lines of assembly to convert bytes to a uint8.

Thoughts?

Do you prefer an alternative approach for requesting the underlying tokens decimals?

This function would be called in the Pod `initialize` function.

```
bytes4 private constant DECIMALS_SELECTOR = bytes4(keccak256(bytes("decimals()")));
        
function getTokenDecimals(address token) internal returns (uint8 value) {
        (bool success, bytes memory data) =
            address(token).call(abi.encodeWithSelector(DECIMALS_SELECTOR));

        require(success, "Pod:invalid-underyling-asset-decimals");

        assembly {
            value := mload(add(data, 0x20))
        }
    }
 ```
 
 In the Pod contract...
 
 ```
...
token = IERC20Upgradeable(_prizePool.token());
ticket = IERC20Upgradeable(tickets[1]);
pool = IERC20Upgradeable(_pool);
faucet = TokenFaucet(_faucet);

// Pod Liquidation Manager
manager = IPodManager(_manager);

// Factory
factory = msg.sender;

uint8 decimals = getTokenDecimals(address(token));

// Configure Decimals to match underlying asset
_setupDecimals(decimals);

// Pod Liquidation Manager
manager = IPodManager(_manager);

// Factory
factory = msg.sender;

uint8 decimals = getTokenDecimals(address(token));

// Configure Decimals to match underlying asset
_setupDecimals(decimals);
 ```

**Comment by asselstine** [comment]
I think this would work for 90% of tokens, but I hesitate to bake the logic directly into the smart contract.

There may also be a future where we *want* a disparity between decimals; for example if people are depositing wBTC we could shift the decimals such that Pod shares are actually fractions of a Bitcoin.

I believe this kind of logic lives best in the client, and that the decimals should be passed into the constructor

**Comment by kamescg** [comment]
Fair point. Will make a pull request that passes decimals in via the constructor/initializer.
